version: '3'

services: 
  nest-todo-api:
    container_name: nest-todo-api
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug 
    env_file: 
      - .env
