version: '3'

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-list-db
    ports:
      - 3306:3306